language: python
sudo: false

env:
  - TOXENV=py27-django18
  - TOXENV=py34-django18
  - TOXENV=py27-django19
  - TOXENV=py34-django19
  # - TOXENV=py35-django19

install:
  - pip install tox

script:
  - tox

after_success:
  - pip install coverage coveralls
  - coverage report
  - coveralls
